### ISSUE TITLE
Participantes como Contribuidores

### ISSUE THREAD

**Issue by jlsilva01** [GuilhermeVolpato/Sistema-Cafeteria#1]
Ola pessoal, onde estão os demais participantes do grupo cadastrados como contribuidores?
Nenhum cadastrado até este momento.

**Comment by GuilhermeVolpato** [comment]
Boa noite professor,

Todos foram convidados no dia em que você passou o trabalho em sala de
aula, mas ainda tem 2 que não aceitaram o convite.

[image: Captura de Tela 2023-06-04 às 18.49.11.png]
Sobre aparecer ali em Contributors, pela minha experiência, os demais só
vão aparecer aqui quando contribuírem de alguma forma, dando commit,
pedindo merge, criando branch ...
mas todos os integrantes já foram convidados certinho.
[image: Captura de Tela 2023-06-04 às 18.50.49.png]



Em dom., 4 de jun. de 2023 às 18:42, Jorge Luiz da Silva <
***@***.***> escreveu:

**Comment by jlsilva01** [comment]
Se cada um atualizar o seu nome no README colocando um hyperlink pra sua conta, já ficará ok.

**Comment by GuilhermeVolpato** [comment]
beleza, vou pedir no grupo para fazerem, valeu

**Comment by GuilhermeVolpato** [comment]
todos já cadastrados como contribuidores!
