### ISSUE TITLE
sistema criado

### ISSUE THREAD

**Issue by Miguelito001** [GuilhermeVolpato/Sistema-Cafeteria#6]
eu criei um sisteminha basico em react, esta bem simples mas funciona, na esquerda voce pode adicionar itens, e na direita aparece o cardapio

**Comment by GuilhermeVolpato** [comment]
boaa

**Comment by GuilhermeVolpato** [comment]
vou adicionar o tailwindcss, pra facilitar o desenvolvimento do front
